# Generated by Django 5.1.7 on 2025-03-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('consumo_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Actual')),
                ('consumo_estimado_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Estimado Mensual')),
            ],
        ),
    ]
