# Generated by Django 5.1.7 on 2025-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentconsumition'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='habitacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
