# Generated by Django 5.1.7 on 2025-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='analisis_emoji',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='analisis_text',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
